# Generated by Django 4.0.3 on 2022-04-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_employee_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_image',
        ),
    ]
