# Generated by Django 4.0.3 on 2022-04-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_remove_employee_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('profile_image', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'db_table': 'employee_pimg',
            },
        ),
    ]
