# Generated by Django 4.0.3 on 2022-04-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_user_passsword_user_role_user_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
